package builder

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/theencryptedafro/appwrap/internal/profile"
	"github.com/theencryptedafro/appwrap/internal/security"
)

type WineStrategy struct{}

func NewWineStrategy() *WineStrategy { return &WineStrategy{} }

func (w *WineStrategy) Name() string { return "wine" }

func (w *WineStrategy) BaseImage(p *profile.AppProfile) string {
	if p.Build.BaseImage != "" {
		return p.Build.BaseImage
	}
	return "ubuntu:22.04"
}

func (w *WineStrategy) GenerateDockerfile(p *profile.AppProfile) (string, error) {
	tmpl, err := template.New("dockerfile").Parse(wineDockerfileTemplate)
	if err != nil {
		return "", fmt.Errorf("parse template: %w", err)
	}

	data := wineTemplateData{
		BaseImage:   w.BaseImage(p),
		AppName:     p.App.Name,
		Arch:        p.Binary.Arch,
		ExeName:     filepath.Base(p.Binary.Path),
		Args:        p.Binary.Args,
		IsGUI:       p.Binary.Subsystem == "gui",
		WineArch:    "win64",
		VCRedists:   p.Dependencies.VCRedist,
		Environment: p.Environment,
	}
	if p.Binary.Arch == "x86" {
		data.WineArch = "win32"
	}

	// Security features
	hasSecurity := security.HasSecurityFeatures(p.Security)
	data.HasSecurity = hasSecurity
	if hasSecurity {
		data.SecuritySnippet = security.SecurityDockerfileSnippet(p.Security)
	}

	// When encrypted, the app lives in /run/appwrap after decryption
	if p.Security.Encryption.Enabled {
		data.AppDir = "/run/appwrap"
	} else {
		data.AppDir = "/home/appuser/app"
	}

	// Build winetricks verbs
	for _, vc := range p.Dependencies.VCRedist {
		switch vc {
		case "vc2015-2022":
			data.WinetricksVerbs = append(data.WinetricksVerbs, "vcrun2022")
		case "vc2013":
			data.WinetricksVerbs = append(data.WinetricksVerbs, "vcrun2013")
		case "vc2012":
			data.WinetricksVerbs = append(data.WinetricksVerbs, "vcrun2012")
		case "vc2010":
			data.WinetricksVerbs = append(data.WinetricksVerbs, "vcrun2010")
		case "vc2008":
			data.WinetricksVerbs = append(data.WinetricksVerbs, "vcrun2008")
		}
	}

	if p.Dependencies.DotNet != nil {
		switch {
		case strings.HasPrefix(p.Dependencies.DotNet.Version, "4"):
			data.WinetricksVerbs = append(data.WinetricksVerbs, "dotnet48")
		}
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template: %w", err)
	}

	return buf.String(), nil
}

func (w *WineStrategy) PrepareContext(p *profile.AppProfile, contextDir string) error {
	// Stage application files
	if err := StageFiles(p, contextDir); err != nil {
		return err
	}

	// Encrypt app files if enabled
	if p.Security.Encryption.Enabled {
		fmt.Println("Encrypting application files with Age...")
		if err := security.EncryptAppFiles(contextDir, p.Security.Encryption); err != nil {
			return fmt.Errorf("encrypt app files: %w", err)
		}
	}

	// Generate firewall script if enabled
	if p.Security.Firewall.Enabled {
		fmt.Println("Generating firewall rules...")
		if err := security.GenerateFirewallScript(contextDir, p.Security.Firewall); err != nil {
			return fmt.Errorf("generate firewall script: %w", err)
		}
	}

	// Prepare WireGuard if enabled
	if p.Security.VPN.Enabled {
		fmt.Println("Preparing WireGuard VPN configuration...")
		if err := security.PrepareWireGuard(contextDir, p.Security.VPN); err != nil {
			return fmt.Errorf("prepare wireguard: %w", err)
		}
	}

	// Generate the master security entrypoint if any security feature is enabled
	if security.HasSecurityFeatures(p.Security) {
		if err := security.GenerateSecurityEntrypoint(contextDir, p.Security); err != nil {
			return fmt.Errorf("generate security entrypoint: %w", err)
		}
	}

	return nil
}

type wineTemplateData struct {
	BaseImage       string
	AppName         string
	Arch            string
	WineArch        string
	ExeName         string
	Args            []string
	IsGUI           bool
	VCRedists       []string
	WinetricksVerbs []string
	Environment     map[string]string
	HasSecurity     bool
	SecuritySnippet string
	AppDir          string
}

const wineDockerfileTemplate = `# Generated by AppWrap — Linux + Wine container for {{ .AppName }}
FROM {{ .BaseImage }}

ENV DEBIAN_FRONTEND=noninteractive

# Install Wine and dependencies
RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        wine64 \
        wine32 \
        winetricks \
        cabextract \
        xvfb \
        ca-certificates \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create app user
RUN useradd -m -s /bin/bash appuser
USER appuser
WORKDIR /home/appuser

# Initialize Wine prefix
ENV WINEPREFIX=/home/appuser/.wine
ENV WINEARCH={{ .WineArch }}
RUN wineboot --init && wineserver --wait
{{ if .WinetricksVerbs }}
# Install runtime dependencies via winetricks
RUN winetricks -q {{ range .WinetricksVerbs }}{{ . }} {{ end }}&& wineserver --wait
{{ end }}
# Copy application files
COPY --chown=appuser:appuser app/ /home/appuser/app/
{{ range $key, $val := .Environment }}
ENV {{ $key }}={{ $val }}
{{ end }}
{{ if .HasSecurity }}
{{ .SecuritySnippet }}
{{ end }}
{{ if .HasSecurity }}
# Security-wrapped entrypoint
ENTRYPOINT ["/usr/local/bin/security-entrypoint.sh"]
{{ if .IsGUI }}
CMD ["xvfb-run", "--auto-servernum", "--server-args=-screen 0 1280x720x24", "wine", "{{ .AppDir }}/{{ .ExeName }}"{{ range .Args }}, "{{ . }}"{{ end }}]
{{ else }}
CMD ["wine", "{{ .AppDir }}/{{ .ExeName }}"{{ range .Args }}, "{{ . }}"{{ end }}]
{{ end }}
{{ else }}
{{ if .IsGUI }}
# GUI app — run with virtual framebuffer
ENTRYPOINT ["xvfb-run", "--auto-servernum", "--server-args=-screen 0 1280x720x24", "wine"]
{{ else }}
# Console app
ENTRYPOINT ["wine"]
{{ end }}
CMD ["/home/appuser/app/{{ .ExeName }}"{{ range .Args }}, "{{ . }}"{{ end }}]
{{ end }}
`
