package cmd

import (
	"fmt"
	"os"
	"sync"

	"github.com/spf13/cobra"
	"github.com/theencryptedafro/appwrap/internal/service"
)

var (
	buildTag      string
	buildNoCache  bool
	buildGenerate string // output dir for generate-only mode
)

var buildCmd = &cobra.Command{
	Use:   "build <profile.yaml>",
	Short: "Build a Docker image from an AppWrap profile",
	Long: `Reads a profile generated by 'appwrap scan', generates a Dockerfile,
stages all required files, and builds a Docker image.`,
	Args: cobra.ExactArgs(1),
	RunE: runBuild,
}

func init() {
	buildCmd.Flags().StringVarP(&buildTag, "tag", "t", "", "image tag (default: <app-name>:latest)")
	buildCmd.Flags().BoolVar(&buildNoCache, "no-cache", false, "build without cache")
	buildCmd.Flags().StringVar(&buildGenerate, "generate", "", "generate Dockerfile + context to this dir without building")
	rootCmd.AddCommand(buildCmd)
}

func runBuild(cmd *cobra.Command, args []string) error {
	svc := service.New(service.WithConfigDir(findConfigDir()))

	events := make(chan service.Event, 256)
	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		for ev := range events {
			switch ev.Kind {
			case service.EventInfo:
				fmt.Println(ev.Message)
			case service.EventProgress:
				fmt.Printf("[%3d%%] %s\n", ev.Percent, ev.Message)
			case service.EventWarning:
				fmt.Printf("Warning: %s\n", ev.Message)
			case service.EventLogLine:
				fmt.Println(ev.Message)
			case service.EventError:
				fmt.Fprintf(os.Stderr, "Error: %s\n", ev.Message)
			case service.EventComplete:
				fmt.Println(ev.Message)
			}
		}
	}()

	result, err := svc.BuildImage(cmd.Context(), service.BuildOpts{
		ProfilePath: args[0],
		Tag:         buildTag,
		NoCache:     buildNoCache,
		GenerateDir: buildGenerate,
	}, events)

	close(events)
	wg.Wait()

	if err != nil {
		return err
	}

	fmt.Printf("\nNext: appwrap run %s\n", result.ImageTag)

	return nil
}
